#states.py
(
    SELECTING_CRYPTO,
    SELECTING_INPUT_TYPE,
    SELECTING_AMOUNT,
    CONFIRMING_DETAILS,
    ENTERING_WALLET,
    CONFIRMING_BONUS,
    SETTING_PARAM,
    SETTING_WALLET
) = range(8)